### PR TITLE
Enable osx-arm64 / linux-{aarch64, ppc64le} builds, add me as maintainer

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks! I just merged the other one, but happy to merge this one right away as well :)

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Builds currently don't get triggered in PRs https://github.com/conda-forge/status/issues/188

**Comment by dbast** [comment]
@conda-forge-admin, please restart ci

**Comment by dbast** [comment]
@conda-forge-admin, please restart ci

**Comment by dbast** [comment]
yay... Azure works again. so ready again for review / marge :)

**Comment by wolfv** [comment]
Thanks!

**Pull request merged**
